### ISSUE TITLE
Question: Uri parsing

### ISSUE THREAD

**Issue by mexx** [freya-fs/arachne#34]
Given an URI, which is not RFC-conform, how should the `Url.Parse` method behave?

```fsharp
let nonConfirm = "http://user%20name:pass@www.example.com:8080/seg1/seg2?key=some%20value&{test}#frag1"
// please note { and } are not percent encoded
Uri.Parse nonConfirm
// results in
Uri
  (Scheme "http",
   Authority
     (Authority
        (Name (RegName "www.example.com"),
         Some (Port 8080),
         Some (UserInfo "user%20name:pass")),
      PathAbsoluteOrEmpty ["seg1"; "seg2"]),
   Some (Query "key=some%20value&"),
   null)
```

Shouldn't it throw in such case, or shouldn't the rule be relaxed to accept this as a valid URI? Formatted version of it can that be correctly percent encoded as required per RFC.

**Comment by mexx** [comment]
One more question, shouldn't the values with percent encoded characters in it, be actually returned decoded?
For the above example `UserInfo "user name:pass"` or `Query "key=some value&"`.
Currently the user is forced to take care of this detail, as well on encoding as decoding site, but it's actually the part of the RFC, right?

**Comment by mexx** [comment]
Further how [URI Comparison for HTTP scheme](https://tools.ietf.org/html/rfc2616#section-3.2.3) fit into the play?

**Comment by mexx** [comment]
Or [http and https URI Normalization and Comparison](https://tools.ietf.org/html/rfc7230#section-2.7.3)

Btw. sorry the many comments, but I discover new worlds here, I think :)

**Comment by kolektiv** [comment]
There's definitely a few interesting cases here :) The parsers are non exhaustive, so it'll parse something which is correct until it stops being correct - if that satisfies the parser, it'll be happy with parsing only some of the input. It's difficult to quite say whether that's the "right" behaviour. I suspect in some cases it might well not be, but we might need to overload the functions to take some option as to whether we want exhaustive parsing or not - whether it should fail.

In terms of percent encoding, i've changed things so that percent encoding/decoding is done via a further optic (so either `raw_` or `decoded_` to work with percent encoded values - effectively because there are some systems which expect to take the original data (URI Templates for one). I'm not 100% convinced that's the best way, or the best implementation yet, and I think that post-3.0 that should get some further work.

Normalization and Comparison... :smile: - yes, I think there's quite a bit of work to do there are some point. I've not implemented it yet purely because it's not been a need - but I'm sure it will be, so I think it probably needs to go in as an issue - along with percent encoding I think, as a placeholder for "better" thinking on that!

No apologies needed :smile:

**Comment by mexx** [comment]
For me there are two different use cases.
 1. One wants to parse a string into the domain context of `Uri` and fail when the input couldn't be processed completely.
 1. One wants to build up a parser pipeline, where one part of the input should be recognized as `Uri`.

IMO `Uri.Parse` should be exhaustive. The underlying parser shouldn't, but should be somehow accessible for the second use case.

**Comment by kolektiv** [comment]
Yes, I would agree. In the latest version of my work on 3.0 I've actually
made the Mapping member, containing the underlying parser, public rather
than internal as it was before. That does mean that the parse method could
now be made exhaustive, as you would expect. That should actually be a
fairly minor change I think. I'll have a quick look!

**Comment by kolektiv** [comment]
Yes, it's actually a pretty tiny change now - I'll make it!

**Comment by kolektiv** [comment]
The exhaustive parsers will be implemented by #37

**Comment by mexx** [comment]
I think the same applies to all of the concepts, not only Uri, right?

**Comment by kolektiv** [comment]
Yup, the latest prerelease version of Arachne works this way - all static
parse methods (on all types which have them) are exhaustive and will fail
if they don't consume all input :)

**Comment by mexx** [comment]
Just saw it's implemented in the core Mapping module ;)

**Comment by kolektiv** [comment]
Yeah - one of those "I'm glad i pulled that out and centralised it" moments
- making that change globally was an additional 10 chars or so :)

**Comment by kolektiv** [comment]
I'm going to close this one as I think it's fixed here (and the implication to Freya Router too). @mexx feel free to comment and I'll re-open if you think it's needed.

**Comment by kolektiv** [comment]
(If you want to create an issue for URI comparison for the 4.0 timeframe I'd be happy with that, given your points here)

**Comment by mexx** [comment]
I'm fine with this for now. If I get into problems with this at some point, I'll raise a new issue, for sure ;)
